# frozen_string_literal: true

# Esempio: ispezione char-level per riconoscimento artefatti.
#
# Mostra come distinguere caratteri "veri" del PDF da quelli inseriti
# da PDFium (es. spazi sintetici), trattini di sillabazione, glifi
# senza mappatura unicode (problemi di font embedding).
#
# Uso: ruby chars_inspect.rb file.pdf [page_index]

require "rpdfium"

input = ARGV[0] or abort "Usage: ruby chars_inspect.rb file.pdf [page_index]"
idx   = (ARGV[1] || 0).to_i

Rpdfium.open(input) do |doc|
  page = doc.page(idx)
  chars = page.chars
  total = chars.size

  generated = chars.count { |c| c[:generated] }
  hyphens   = chars.count { |c| c[:hyphen] }
  errors    = chars.count { |c| c[:unicode_error] }
  rotated   = chars.count { |c| c[:angle].abs > 0.01 }
  invisible = chars.count { |c| c[:render_mode] == 3 }

  puts "Page #{idx + 1}: #{total} chars"
  puts "  Generated by PDFium (synth spaces): #{generated}"
  puts "  Soft hyphens (line break artefacts): #{hyphens}"
  puts "  Unicode mapping errors:              #{errors}"
  puts "  Rotated glyphs:                      #{rotated}"
  puts "  Invisible (render_mode=3):           #{invisible}"

  # Esempio: testo "pulito" filtrando gli artefatti
  clean = chars.reject { |c| c[:generated] || c[:unicode_error] }
               .map    { |c| c[:char] }.join
  puts "\nCleaned text (first 200 chars):"
  puts clean[0, 200]

  # Font usati (utile per capire se ci sono font embedded sospetti)
  fonts = chars.map { |c| [c[:font], c[:weight]] }.tally
  puts "\nFonts detected:"
  fonts.sort_by { |_, n| -n }.first(10).each do |(name, weight), n|
    puts "  #{name.inspect} (weight=#{weight}): #{n} chars"
  end
end
